django/mysite/mysite/urls.py
from django.conf.urls import url, patterns
from django.contrib import admin
from mysite.views import hello, current_datetime, hours_ahead, display_meta
from books import views
from contact.views import  contact, thanks


urlpatterns = patterns('mysite.views',
    url(r'^hello/$', 'hello'),
    url(r'time/$', 'current_datetime'),
    url(r'^time/plus/(\d{1,2})/$', 'hours_ahead'),
)

urlpatterns += [
    url(r'^admin/', admin.site.urls),
    url(r'^display_meta/$', display_meta),
    #url(r'^search-form/$', views.search_form),
    url(r'^search/$', views.search),
    url(r'^contact/$', contact),
    url(r'^contact/thanks/$', thanks)
]

django/mysite/books/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
    
class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')
    
    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)    
    
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    
    def __unicode__(self):
        return self.title    

django/mysite/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)
    
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

django/mysite/books/views.py
from django.shortcuts import render
from books.models import Book

# Create your views here.
from django.shortcuts import render_to_response
from django.http import HttpResponse

def search(request):
    error = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            error.append('Enter a search term.')
        elif len(q) > 20:
            error.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('search_results.html',
                                              {'books': books, 'query': q})            
    return render_to_response('search_form.html', {'errors': error})

#def search(request):
    #if 'q' in request.GET and request.GET['q']:
        #q = request.GET['q']
        #books = Book.objects.filter(title__icontains=q)
        #return render_to_response('search_results.html',
                                  #{'books': books, 'query': q})
    #else:
        ##return HttpResponse('Please submit a search term.')
        #return render_to_response('search_form.html', {'error': True})

django/mysite/contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response
from contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            #send_mail(
                #cd['subject'],
                #cd['message'],
                #cd.get('email', 'noreply@example.com'),
                #['siteowner@example.com'],
            #)
            return HttpResponseRedirect('/contact/thanks')
    else:
        form = ContactForm(
            initial = {'subject': 'I love your site!'}
        )
    return render_to_response('contact_form.html', {'form': form})
    
def thanks(request):
    return HttpResponse('Mail send success!!!')

django/mysite/mysite/views.py
from django.http import HttpResponse, Http404
import datetime

def hello(request):
    return HttpResponse("Hello world")

def current_datetime(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>" % now
    return HttpResponse(html)

def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
    html = "<html><body>In %s hour(s), it will be %s.</body></html>" % (offset, dt)
    return HttpResponse(html)


def display_meta(request):
    values = request.META.items()
    values.sort()
    html = ['<tr><td>%s</td><td>%s</td></tr>' % ('request.path', request.path),
            '<tr><td>%s</td><td>%s</td></tr>' % ('request.get_host()', request.get_host()),
            '<tr><td>%s</td><td>%s</td></tr>' % ('request.get_full_path()', request.get_full_path()),
            '<tr><td>%s</td><td>%s</td></tr>' % ('request.is_secure()', str(request.is_secure())),
            ]
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))

django/mysite/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>
    
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} blew.
        </p>
    {% endif %}
    
    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>

django/mysite/templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="", method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

django/mysite/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}